# Generated by Django 2.0.1 on 2018-11-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.IntegerField(unique=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicle', to='service.Vehicle')),
            ],
        ),
    ]
