# Generated by Django 2.0.1 on 2018-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='engine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_plate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
