# Generated by Django 2.0.1 on 2018-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
