# Generated by Django 2.0.1 on 2018-11-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20181107_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.FloatField(),
        ),
    ]
