# Generated by Django 2.0.1 on 2018-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20181107_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
