# Generated by Django 2.0.1 on 2018-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20181107_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.BooleanField(default=0),
        ),
    ]
