# Generated by Django 2.0.1 on 2018-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20181107_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
