# Generated by Django 2.0.1 on 2018-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20181107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
