# Generated by Django 2.0.1 on 2018-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20181107_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.NullBooleanField(default=0),
        ),
    ]
