# Generated by Django 2.0.1 on 2018-11-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20181107_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complain',
            new_name='complaint',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
