# Generated by Django 2.0.1 on 2018-11-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20181109_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_vehicle', to='service.Vehicle'),
        ),
    ]
