# Generated by Django 2.1.3 on 2018-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20181109_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='item_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
