# Generated by Django 2.1.3 on 2018-11-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_bill_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_no',
            field=models.IntegerField(null=True),
        ),
    ]
