# Generated by Django 2.1.3 on 2018-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_order_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_call',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='enter_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
